#!/bin/bash

DESCRIPTION="check conntrack table"

init() {
    # permit up to 95% of usage
    CONNTRACK_WARNING_RATIO=95
    true
}

run() {

    explain "checking conntrack table"

    local RETURN=$CHECK_SUCCESS

    if [ ! -e /proc/sys/net/netfilter/nf_conntrack_max ] || [ ! -e /proc/sys/net/netfilter/nf_conntrack_count ]
    then
        abort "/proc/sys/net/netfilter/nf_conntrack_{count,max} not found, conntrack may not be loaded"
        return $CHECK_IGNORED
    fi

    local CONNTRACK_MAX=$(cat /proc/sys/net/netfilter/nf_conntrack_max)
    local CONNTRACK_COUNT=$(cat /proc/sys/net/netfilter/nf_conntrack_count)

    local RATIO=$(( $CONNTRACK_COUNT * 100 / $CONNTRACK_MAX ))

    echo "conntrack usage $CONNTRACK_COUNT, max: $CONNTRACK_MAX, ratio: $RATIO%"

    if [[ $RATIO -gt $CONNTRACK_WARNING_RATIO ]]
    then
        # note: could also use dmesg
        alert "conntrack table is over limit: usage $CONNTRACK_COUNT, max: $CONNTRACK_MAX, ratio: $RATIO%"
        RETURN=$(max $? $RETURN)
    fi

    local LINE TOTAL_EARLY_DROP PREV_TOTAL_EARLY_DROP
    TOTAL_EARLY_DROP=0
    LINE=0

    if [ -e /proc/net/stat/nf_conntrack ]
    then
        # this part may be deprecated in the future, replaced with conntrack binary
	echo "using /proc/net/stat/nf_conntrack"

        local entries clashres found new invalid ignore delete chainlength insert insert_failed drop early_drop icmp_error  expect_new expect_create expect_delete search_restart
        while read -r entries clashres found new invalid ignore delete chainlength insert insert_failed drop early_drop icmp_error  expect_new expect_create expect_delete search_restart
        do
            LINE=$(($LINE+1))
            # ignore first line
            [[ $LINE -eq 1 ]] && continue
            # values are in hexa
            TOTAL_EARLY_DROP=$((16#$early_drop + $TOTAL_EARLY_DROP))
        done < <(cat /proc/net/stat/nf_conntrack)

    elif which conntrack >/dev/null 2>/dev/null
    then
	echo "using conntrack binary"

	local cpu found invalid insert insert_failed drop early_drop error search_restart clash_resolve chaintoolong
	while read -r cpu found invalid insert insert_failed drop early_drop error search_restart clash_resolve chaintoolong
	do
	    # keep only numerical value
	    TOTAL_EARLY_DROP=$(( ${early_drop#*=} + $TOTAL_EARLY_DROP))
	done < <(conntrack --stats)

    else
	warn "/proc/net/stat/nf_conntrack is not available and conntrack (apt install conntrack) is not found [conntrack drop count impossible]"
	return $(max $? $RETURN)
    fi

    PREV_TOTAL_EARLY_DROP=0
    if [ -e $HT_RUNDIR/conntrack_drop ]
    then
        echo "using previous counter $HT_RUNDIR/conntrack_drop"
        PREV_TOTAL_EARLY_DROP=$(cat $HT_RUNDIR/conntrack_drop)
    fi

    if [[ $TOTAL_EARLY_DROP -eq $PREV_TOTAL_EARLY_DROP ]]
    then
        echo "no new conntrack drop (last value: $PREV_TOTAL_EARLY_DROP)"
    else
        alert "found $(( $TOTAL_EARLY_DROP - $PREV_TOTAL_EARLY_DROP )) new conntrack drops due to table full, remove alert setting $TOTAL_EARLY_DROP in $HT_RUNDIR/conntrack_drop"
        RETURN=$(max $? $RETURN)
    fi

    return $RETURN
}
