#!/bin/bash

DESCRIPTION="check load avg in 15min"

run() {

    explain "check load avg in 15min"
    local LOADAVG=$(cat /proc/loadavg | awk '{print $3}')
    local LOADAVG_ROUNDED=$( echo $LOADAVG | awk '{ print int($1+0.5) }')
    local CPUCOUNT=$(grep -c ^processor /proc/cpuinfo)

    # Alert on round(LOADAVG) > #CPU+1
    if [ $LOADAVG_ROUNDED -gt $(($CPUCOUNT+1)) ]
    then
        alert "cpu loadavg (on 15min) is high: $LOADAVG (cpu count: $CPUCOUNT)"
    fi

    explain "check for blocked processes (in IOWait for example)"
    local PROCSBLOCKED=$(grep procs_blocked /proc/stat | awk '{print $2}')
    if [ $PROCSBLOCKED -gt 5 ]
    then
        alert "found many blocked processes ($PROCSBLOCKED)"
    fi

}


