#!/bin/bash

DESCRIPTION="check disk health and temperature"

init() {
    SILENT_BADSECTOR=()
    BADSECTORLIMIT=0
    BADTEMPLIMIT=50
}

run() {

    if detect_virt
    then
        abort "this is a virtual machine, test is not relevant [ignoring test]"
        return $CHECK_IGNORED
    fi

    if [ -z "$(find_disks sd)" ]
    then
        abort "no SSD/HD found [ignoring test]"
        return $CHECK_IGNORED
    fi

    if ! which smartctl >/dev/null
    then
        abort "smartctl not installed (fix: apt-get install smartmontools) [ignoring test]"
        return $CHECK_IMPOSSIBLE
    fi

    local RETURN=$CHECK_SUCCESS

    #if which lshw >/dev/null
    #then
    #       # disk list
    #       DISKS=$(lshw -class disk -short -quiet | tail -n +3 | awk '{ print $2; }')
    #else
    #       echo "lshw not installed get disk list via /dev/disk (better via: apt-get install lshw)"
    #       DISKS=$(readlink -f /dev/disk/by-id/* | grep -e '[a-z]$' | sort | uniq )
    #fi

    local DISK SHORT

    local do_alert="alert"

    # foreach disk
    for DISK in $( find_disks sd)
    do
        SHORT="${DISK##*/}"

        local SELFVARDIR="$VARDIR/$CLASS/$MODULE/$SHORT"
        test -e $SELFVARDIR || mkdir -p $SELFVARDIR

        explain "checking sd disk $DISK"
        if [ -e "/sys/block/$SHORT/queue/rotational" ]
        then
            if [ $(cat "/sys/block/$SHORT/queue/rotational") == 1 ]
            then
                echo "$DISK seems to be a HDD"
            else
                echo "$DISK seems to be a SSD"
            fi
        else
            echo "$DISK is neither a HDD nor a SSD"
        fi

        # get uniq WWN - World Wide Name
        # note: ID_SERIAL works too, WWN is recommanded
        local W
        local UNIQ_ID
        for W in /dev/disk/by-id/wwn-* #/dev/disk/by-id/nvme-eui.*
        do
            if [[ $(readlink -f $W) = /dev/$SHORT ]]
            then
                # keep number only
                UNIQ_ID=${W##*/wwn-}
                break
            fi
        done

        # could have used:
        # UNIQ_ID=$(udevadm info --query=property --name=/dev/$SHORT | grep ID_WWN= | cut -d = -f 2)

        if [[ -z "$UNIQ_ID" ]]
        then
            $do_alert "failed to get uniq uniq id (WWN) from $DISK"
            RETURN=$(max $? $RETURN)
        else
            echo $DISK has uniq id wwn:$UNIQ_ID
            if [[ -e $SELFVARDIR/uniq_id ]]
            then
                local PREV_UNIQ_ID=$(cat $SELFVARDIR/uniq_id)
                # check that identifiant has not changed
                if [[ "$PREV_UNIQ_ID" != "$UNIQ_ID" ]]
                then
                    $do_alert "$DISK has changed (current UNIQ_ID $UNIQ_ID differs from previous $PREV_UNIQ_ID) please check your hardware or update $SELFVARDIR/uniq_id"
                    RETURN=$(max $? $RETURN)
                fi
            else
                # store identifiant
                echo $UNIQ_ID > $SELFVARDIR/uniq_id
            fi
        fi

        # foreach smartctl

        # smartctl 6.6 2017-11-05 r4594 [x86_64-linux-4.19.0-8-amd64] (local build)
        # Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org
        #
        # === START OF READ SMART DATA SECTION ===
        # SMART Attributes Data Structure revision number: 16
        # Vendor Specific SMART Attributes with Thresholds:
        # ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
        #   1 Raw_Read_Error_Rate     0x000b   100   100   016    Pre-fail  Always       -       0
        #   2 Throughput_Performance  0x0005   136   136   054    Pre-fail  Offline      -       80
        #   3 Spin_Up_Time            0x0007   193   193   024    Pre-fail  Always       -       248 (Average 399)
        #   4 Start_Stop_Count        0x0012   100   100   000    Old_age   Always       -       16
        #   5 Reallocated_Sector_Ct   0x0033   100   100   005    Pre-fail  Always       -       0
        #   7 Seek_Error_Rate         0x000b   100   100   067    Pre-fail  Always       -       0
        #   8 Seek_Time_Performance   0x0005   145   145   020    Pre-fail  Offline      -       24
        #   9 Power_On_Hours          0x0012   095   095   000    Old_age   Always       -       39172
        #  10 Spin_Retry_Count        0x0013   100   100   060    Pre-fail  Always       -       0
        #  12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       16
        # 192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       16
        # 193 Load_Cycle_Count        0x0012   100   100   000    Old_age   Always       -       16
        # 194 Temperature_Celsius     0x0002   166   166   000    Old_age   Always       -       36 (Min/Max 18/49)
        # 196 Reallocated_Event_Count 0x0032   100   100   000    Old_age   Always       -       0
        # 197 Current_Pending_Sector  0x0022   100   100   000    Old_age   Always       -       0
        # 198 Offline_Uncorrectable   0x0008   100   100   000    Old_age   Offline      -       0
        # 199 UDMA_CRC_Error_Count    0x000a   200   200   000    Old_age   Always       -       0


        local ID ATTRIBUTE_NAME FLAG VALUE WORST THRESH TYPE UPDATED WHEN_FAILED RAW_VALUE
        while read -r ID ATTRIBUTE_NAME FLAG VALUE WORST THRESH TYPE UPDATED WHEN_FAILED RAW_VALUE
        do
            [ -z "$ATTRIBUTE_NAME" ] && continue
            [ -z "$RAW_VALUE" ] && continue

            # debug echo "$DISK $ATTRIBUTE_NAME $RAW_VALUE"

            local do_alert="alert"
            contains "$DISK" "${SILENT_BADSECTOR[@]}" && do_alert="silent_alert"

            # source: https://en.wikipedia.org/wiki/S.M.A.R.T.#Known_ATA_S.M.A.R.T._attributes
            case "$ID" in
                "5")
                    #id=5 "Reallocated_Sector_Ct" (bad for HD and SSD)
                    echo "INFO: Reallocated Sector Count: $RAW_VALUE"
                    if [ $RAW_VALUE -gt $BADSECTORLIMIT ]
                    then
                        $do_alert "$DISK has $RAW_VALUE bad sectors";
                        RETURN=$(max $? $RETURN)
                    fi
                    ;;
                "7")
                    #id=5 "Spin_Retry_Count" (bad for HD)
                    # https://kb.acronis.com/content/9110
                    echo "INFO: Spin Retry Count: $RAW_VALUE"
                    # TODO: warn if growing up [ $RAW_VALUE -gt $BADSECTORLIMIT ] && $do_alert "$DISK has $RAW_VALUE spin retry";
                    ;;

                "187")
                    #id=187 "Reported Uncorrectable Errors"    (bad SSD)
                    local REPORTED_UNCORRECT=0
                    if [ -e $SELFVARDIR/Reported_Uncorrect ]
                    then
                       echo "using $SELFVARDIR/Reported_Uncorrect as reference"
                       REPORTED_UNCORRECT=$(cat $SELFVARDIR/Reported_Uncorrect)
                    fi

                    echo "INFO: Reported Uncorrectable Errors: $RAW_VALUE (previously $REPORTED_UNCORRECT)"
                    if [ $RAW_VALUE -gt $REPORTED_UNCORRECT ]
                    then
                        $do_alert "$DISK has $RAW_VALUE uncorrectable errors (please store in $SELFVARDIR/Reported_Uncorrect)";
                        RETURN=$(max $? $RETURN)
                    fi
                    ;;

                "188")
                    #id=188 "Command Timeout"
                                        RAW_VALUE="${RAW_VALUE%% *}" # remove all YY in "XX YY"
                   local CMD_TIMEOUT_LIMIT=0
                   # FIXME: make it generic
                   if [ -e $SELFVARDIR/Command_Timeout ]
                   then
                       echo "using $SELFVARDIR/Command_Timeout as reference"
                       CMD_TIMEOUT_LIMIT=$(cat $SELFVARDIR/Command_Timeout)
                    fi

                    echo "INFO: Reported command timeout: $RAW_VALUE (previously $CMD_TIMEOUT_LIMIT)"
                    if [ $RAW_VALUE -gt $CMD_TIMEOUT_LIMIT ]
                    then
                        $do_alert "$DISK has $RAW_VALUE command timeout (please store in $SELFVARDIR/Command_Timeout)";
                        RETURN=$(max $? $RETURN)
                    fi
                    ;;

                "194")
                    #id=194 Temperature_Celsius
                                        RAW_VALUE="${RAW_VALUE%% *}" # remove all YY in "XX YY"
                    echo "INFO: Temperature Celsius: $RAW_VALUE"
                    if [ $RAW_VALUE -gt $BADTEMPLIMIT ]
                    then
                        $do_alert "$DISK has temperature $RAW_VALUE too high";
                        RETURN=$(max $? $RETURN)
                    fi
                    ;;

                "196")
                    #id=196 "Reallocation Event Count"
                    echo "INFO: Reported command timeout: $RAW_VALUE"
                    ;;

                "197")
                    #id=197 "Current_Pending_Sector"
                    echo "INFO: Current Pending Sector: $RAW_VALUE"
                    if [ $RAW_VALUE -gt $BADSECTORLIMIT ]
                    then
                        $do_alert "$DISK has $RAW_VALUE coming bad sectors";
                        RETURN=$(max $? $RETURN)
                    fi
                    ;;

                "201")
                    #id=201    "Soft Read Error Rate"
                    # https://kb.acronis.com/content/9137
                    RAW_VALUE="${RAW_VALUE%%/*}" # remove all /YY in "XX/YY"
                    echo "INFO: Soft read error: $RAW_VALUE"
                    # TODO: WARN if growing up [ $RAW_VALUE -gt $BADSECTORLIMIT ] && $do_alert "$DISK has $RAW_VALUE read errors";
                    ;;

            esac

        done < <( smartctl -A /dev/$DISK 2>/dev/null )
    done

    return $RETURN
}

