#!/bin/bash

DESCRIPTION="check specified file existance"

init() {
    MANDATORY_FILES=()
}

run() {
    if [ ${#MANDATORY_FILES[@]} == 0 ]
    then
        abort "no imandatory file to check"
        return $CHECK_DISABLED
    fi

    local RETURN=$CHECK_SUCCESS

    local FILE NEGATE
    for FILE in ${MANDATORY_FILES[@]}
    do
        if [[ "$FILE" =~ ^- ]]
        then
            FILE="${FILE:1}"
            NEGATE="!"
            explain "checking that $FILE does not exist"
        else
            NEGATE=""
            explain "checking that $FILE exists"
        fi

        if [ $NEGATE ! -e $FILE ]
        then
            alert "$FILE does not exist, please check"
            RETURN=$(max $? $RETURN)
        fi
    done

    return $RETURN
}


