#!/bin/bash

DESCRIPTION="check specified file existance"

init() {
    MANDATORY_FILES=()
}

run() {
    if [ ${#MANDATORY_FILES[@]} == 0 ]
    then
        abort "no imandatory file to check"
        return $CHECK_DISABLED
    fi

    local RETURN=$CHECK_SUCCESS

    local FILE
    for FILE in ${MANDATORY_FILES[@]}
    do
        explain "checking that $FILE exists"
        if [ ! -e $FILE ]
        then
            alert "$FILE does not exist, please check"
            RETURN=$(max $? $RETURN)
        fi
    done

    return $RETURN
}


