#!/bin/bash

DESCRIPTION="warn on hardware device change"

init() {
    true
}

run() {

    explain "check hardware change"

    if detect_virt
    then
        abort "this is a virtual machine, test is not relevant [ignoring test]"
        return $CHECK_IGNORED
    fi

    local RETURN=$CHECK_SUCCESS
    local DIFF

    local SELFVARDIR="$VARDIR/$CLASS/$MODULE"
    test -e $SELFVARDIR || mkdir -p $SELFVARDIR

    if [ ! -e /sys/bus/pci ] && [ ! -e /sys/bus/pci_express ]
    then
        echo "no PCI devices, ignoring this section"
    else

        if ! which lspci >/dev/null
        then
            # note: could also use dmesg
            abort "lspci not installed (fix via: apt install pciutils)"
            return $CHECK_IMPOSSIBLE
        fi

        if [ ! -e $SELFVARDIR/lspci ]
        then
            echo "INFO: storing lspci"
            lspci | sort > $SELFVARDIR/lspci
        else
            lspci | sort > $SELFVARDIR/lspci.latest
            if DIFF="$(diff -u1 $SELFVARDIR/lspci $SELFVARDIR/lspci.latest | tail -n +3 | grep -e '^[+-]'; exit ${PIPESTATUS[0]})"
            then
                echo "INFO: lspci unchanged"
            else
                alert "PCI devices changed:"$'\n'"$DIFF"
                RETURN=$(max $? $RETURN)
                echo "remove $SELFVARDIR/lspci.latest extension to acknowledge"
            fi
        fi
    fi

    if [ ! -e /sys/bus/usb ]
    then
        echo "no USB devices, ignoring this section"
    else
        if ! which lsusb >/dev/null
        then
            # note: could also use dmesg
            abort "lsusb not installedi (fix via: apt install usbutils)"
            return $CHECK_IMPOSSIBLE
        fi

        if [ ! -e $SELFVARDIR/lsusb ]
        then
            echo "INFO: storing lsusb"
            lspci | sort > $SELFVARDIR/lsusb
        else
            lspci | sort > $SELFVARDIR/lsusb.latest
            if DIFF="$(diff -u1 $SELFVARDIR/lsusb $SELFVARDIR/lsusb.latest | tail -n +3 | grep -e '^[+-]'; exit ${PIPESTATUS[0]})"
            then
                echo "INFO: lsusb unchanged"
            else
                alert "USB devices changed:"$'\n'"$DIFF"
                RETURN=$(max $? $RETURN)
                echo "remove $SELFVARDIR/lsusb.latest extension to acknowledge"
            fi
        fi
    fi

    return $RETURN
}
