#!/bin/bash

DESCRIPTION="lookup hardware warning in journal"

init() {
    KERNEL_CRITICAL_IGNORE=""
    KERNEL_CRITICAL_REGEX="Timeout waiting for hardware interrupt|BTRFS warning"
}

run() {

    explain "check hardware warnings since 24h"

    if ! which journalctl >/dev/null
    then
        # note: could also use dmesg
        abort "journalctl not found [ignoring test]"
        return $CHECK_IMPOSSIBLE
    fi

    local RETURN=$CHECK_SUCCESS

    # -p2 = alert & crit
    if [ ! -z "$HARDWARE_WARNING_IGNORE" ]
    then
        return $CHECK_DISABLED
    fi
    journalctl -p warning --system --since="$(date --iso --date='1day ago')" "_TRANSPORT=kernel" | grep -E "$KERNEL_CRITICAL_REGEX" | sed 's/^/  /' >> $TMPDIR/hardwarewarning

    # if file is non empty
    if [ -s $TMPDIR/hardwarewarning ]
    then
        cat $TMPDIR/hardwarewarning
        warn "found hardwarek warnings: " $(tail -n 1 $TMPDIR/hardwarewarning)
        RETURN=$(max $? $RETURN)
    fi

    rm -f $TMPDIR/hardwarewarning

    return $RETURN
}
