#!/bin/bash

DESCRIPTION="check ipv6"

init() {
    CHECK_IPV6="NO" # default no
}

run() {

    if ( ! to_boolean $CHECK_IPV6 )
    then
        echo "ignore ipv6 check"
        return $CHECK_IGNORED
    fi

    explain "checking ipv6"

    if ! which curl >/dev/null
    then
        alert "curl not found (fix via: apt-get install curl)"
        return $CHECK_IMPOSSIBLE
    fi

    local IPV6=$(curl -s -6 https://ifconfig.me)

    if [ $? != 0 ]
    then
        alert "ipv6 connection test failed"
    else
        echo "ipv6 working, outgoing IP is $IPV6"
    fi

}

