#!/bin/bash

DESCRIPTION="check ipv6"

init() {
    CHECK_IPV6="NO" # default no
}

run() {

    if ( ! to_boolean $CHECK_IPV6 )
    then
        echo "ignore ipv6 check"
        return $CHECK_IGNORED
    fi

    explain "checking ipv6"

    if ! which curl >/dev/null
    then
        alert "curl not found (fix via: apt-get install curl)"
        return $CHECK_IMPOSSIBLE
    fi

    RETURN=$CHECK_SUCCESS

    local V6_DEFAULT_GW=$(ip -6 route show default)
    if [ -z "$V6_DEFAULT_GW" ]
    then
        alert "did not found a default ipv6 gateway"
        RETURN=$CHECK_FAILED
    else
        echo "default route is/are: $V6_DEFAULT_GW"
    fi

    local IPV6
    IPV6=$(curl -s -6 https://ifconfig.me)

    if [ $? -ne 0 ]
    then
        alert "ipv6 HTTP connection test failed"
        RETURN=$CHECK_FAILED
    else
        echo "ipv6 working, outgoing IP is $IPV6"
    fi

    return $CHECK_SUCCESS

}

