#!/bin/bash

DESCRIPTION="replace me"

init() {
    KERNEL_CRITICAL_IGNORE=""
}

run() {

    explain "check critical kernel message since 3 days"

    if ! which journalctl >/dev/null
    then
        # note: could also use dmesg
        abort "journalctl not found [ignoring test]"
        return
    fi

    # -p2 = alert & crit
    if [ -z "$KERNEL_CRITICAL_IGNORE" ]
    then
        journalctl -b -k -e -p2 -q -x --no-pager --since="$(date --iso --date='3day ago')" >/tmp/critmsg
    else
        journalctl -b -k -e -p2 -q -x --no-pager --since="$(date --iso --date='3day ago')" | grep -v -E "$KERNEL_CRITICAL_IGNORE" >/tmp/critmsg
    fi

    # if file is non empty
    if [ -s /tmp/critmsg ]
    then
        cat /tmp/critmsg
        alert "found critical kernel message " $(tail -n 1 /tmp/critmsg)
    fi

    rm -f /tmp/critmsg

}


