#!/bin/bash

DESCRIPTION="ensure specified partition mount"

init() {
    PARTITIONS=()
}

run() {
    if [ ${#PARTITIONS[@]} == 0 ]
    then
        abort "no mount point to check"
        return $CHECK_DISABLED
    fi

    local RETURN=$CHECK_SUCCESS

    # check data mounted
    local DATA
    for DATA in ${PARTITIONS[@]}
    do
        # follow link if necessary
        if [ -L $DATA ]
        then
            TARGET=$(readlink -f $DATA)
            if [ -z "$TARGET" ]
            then
                alert "wrong symlink $DATA"
                RETURN=$(max $? $RETURN)
                continue
            fi
            DATA=$TARGET
        fi
        explain "checking partition $DATA is mounted"

        if ! mountpoint -q $DATA
        then
            alert "$DATA not mounted"
            RETURN=$(max $? $RETURN)
        fi
    done

    return $RETURN
}

