#!/bin/bash

DESCRIPTION="ensure specified partition mount"

init() {
    PARTITIONS=()
}

run() {
    if [ ${#PARTITIONS[@]} == 0 ]
    then
        abort "no mount point to check"
        return $CHECK_DISABLED
    fi

    # check data mounted
    local DATA
    for DATA in ${PARTITIONS[@]}
    do
        # follow link if necessary
        if [ -L $DATA ]
        then
            TARGET=$(readlink -f $DATA)
            if [ -z "$TARGET" ]
            then
                alert "wrong symlink $DATA"
                continue
            fi
            DATA=$TARGET
        fi
        explain "checking partition $DATA is mounted"

        mountpoint -q $DATA || alert "$DATA not mounted"
    done

}

