#!/bin/bash

DESCRIPTION="ensure no root password"

init() {
    ALLOW_ROOT_PASSWORD="NO"
}

run() {
    # because I prefer keys

    to_boolean $ALLOW_ROOT_PASSWORD && echo "allow root password" && return

    explain "checking no root password"

    local ROOT_PASS=$(getent shadow root | cut -d : -f 2)
    [ "$ROOT_PASS" != "*" ] && alert "this server has a root password, please use ssh key"
}


