#!/bin/bash

DESCRIPTION="ensure no root password"

init() {
    ALLOW_ROOT_PASSWORD="NO"
}

run() {
    # because I prefer keys

    if to_boolean $ALLOW_ROOT_PASSWORD
    then
        echo "root password are premitted"
        return $CHECK_DISABLED
    fi

    explain "checking no root password"

    local ROOT_PASS=$(getent shadow root | cut -d : -f 2)
    if [ "$ROOT_PASS" != "*" ]
    then
        alert "this server has a root password, please use ssh key"
        return $CHECK_FAILED
    fi

    return $CHECK_SUCCESS

}


