#!/bin/bash

DESCRIPTION="check nvme health and temperature"

init() {
    SILENT_BADSECTOR=()
    BADSECTORLIMIT=0
    BADTEMPLIMIT=50
}

run() {

    if detect_virt
    then
        abort "this is a virtual machine, test is not relevant [ignoring test]"
        return $CHECK_IGNORED
    fi

    if ! grep -q nvme /proc/devices
    then
        abort "no nvme found [ignoring test]"
        return $CHECK_IGNORED
    fi

    if ! which nvme >/dev/null
    then
        abort "nvme not installed (fix: apt-get install nvme-cli) [ignoring test]"
        return $CHECK_IMPOSSIBLE
    fi

    if ! which jq >/dev/null
    then
        abort "jq not installed (fix: apt-get install jq) [ignoring test]"
        return $CHECK_IMPOSSIBLE
    fi

    local RETURN=$CHECK_SUCCESS

    local DISK SHORT CRITICAL

    # foreach disk
    for DISK in $( find_disks blkext)
    do
        SHORT="${DISK##*/}"

        local do_alert=alert

        local SELFVARDIR="$VARDIR/$CLASS/$MODULE/$DISK"
        test -e $SELFVARDIR || mkdir -p $SELFVARDIR

	    explain "checking nvme disk $SHORT"

        # get uniq WWN - World Wide Name (EUI for nvme disks)
        # note: ID_SERIAL works too, WWN is recommanded
        local W
        local UNIQ_ID
        for W in /dev/disk/by-id/nvme-eui.*
        do
            if [[ $(readlink -f $W) = /dev/$SHORT ]]
            then
                # keep number only
                UNIQ_ID=${W##*/nvme-}
                break
            fi
        done

        # could have used:
        # UNIQ_ID=$(udevadm info --query=property --name=/dev/$SHORT | grep ID_WWN= | cut -d = -f 2)

        if [[ -z "$UNIQ_ID" ]]
        then
            $do_alert "failed to get uniq uniq id (EUI) from $DISK"
            RETURN=$(max $? $RETURN)
        else
            echo $DISK has uniq id $UNIQ_ID
            if [[ -e $SELFVARDIR/uniq_id ]]
            then
                local PREV_UNIQ_ID=$(cat $SELFVARDIR/uniq_id)
                # check that identifiant has not changed
                if [[ "$PREV_UNIQ_ID" != "$UNIQ_ID" ]]
                then
                    $do_alert "$DISK has changed (current UNIQ_ID $UNIQ_ID differs from previous $PREV_UNIQ_ID) please check your hardware or update $SELFVARDIR/uniq_id"
                    RETURN=$(max $? $RETURN)
                fi
            else
                # store identifiant
                echo $UNIQ_ID > $SELFVARDIR/uniq_id
            fi
        fi

	    CRITICAL=$(nvme smart-log /dev/$DISK -o json | jq -r .critical_warning)

        if [[ $CRITICAL -gt 0 ]]
        then
            $do_alert "$SHORT has critical warnings";
            RETURN=$(max $? $RETURN)
            nvme smart-log /dev/$DISK
        else
            echo "$SHORT is clean"
        fi

        echo
    done

    return $RETURN
}

