#!/bin/bash

DESCRIPTION="replace me"

run() {

    explain "check oomkilled process since 1 day"

    # to get number of oom kill since boot time:
    # awk '{if($1 == "oom_kill") {print $2}}' < /proc/vmstat

    if which journalctl >/dev/null
    then
        # try via systemctl
        # -p4 = warning
        journalctl -b -k -e -p4 -x -q --no-pager --since="$(date --iso --date='1day ago')" | grep -E -i 'killed process|out of memory' > /tmp/oom.list
    elif [ -e /var/log/kern.log ]
    then
        # try via messages
        grep -E -i 'killed process|out of memory' /var/log/kern.log > /tmp/oom.list
    elif [ -e /var/log/messages ]
    then
        # try via messages
        grep -E -i 'killed process|out of memory' /var/log/messages > /tmp/oom.list
    else
        abort "neither journalctl nor kern.log/messages where found, cannot check oomkilled [ignoring test]"
        return
    fi

    # if file is non empty
    if [ -s /tmp/oom.list ]
    then
        cat /tmp/oom.list
        alert "found out of memory processes " $(tail -n 1 /tmp/oom.list)
    fi

    rm -f /tmp/oom.list
}


