#!/bin/bash

DESCRIPTION="check volume remaining space"

init() {
    DISKLIMIT=75
}

run() {

    local RETURN=$CHECK_SUCCESS

    local PARTITION FSTYPE IPCENT PCENT
    while read -r PARTITION FSTYPE IPCENT PCENT
    do
        IPCENT=${IPCENT%?}
        PCENT=${PCENT%?}

        explain "checking partition $PARTITION"

        if [ $PCENT -ge $DISKLIMIT ]
        then
            alert "$PARTITION reached size limit: $PCENT %"
        else
            echo "$PARTITION size ok ($PCENT %)"
        fi

        [ -z "$IPCENT" ] && continue

        if [ $IPCENT -ge $DISKLIMIT ]
        then
            alert "$PARTITION reached inode size limit: $IPCENT %"
            RETURN=$CHECK_FAILED
        else
            echo "$PARTITION inode size ok ($IPCENT %)"
        fi

    done < <( df -l --exclude-type="devtmpfs" --exclude-type="tmpfs" --exclude-type="overlay" --output="source,fstype,ipcent,pcent" | tail -n +2 )

    return $RETURN
}

