#!/bin/bash

DESCRIPTION="ensure specified partition writable"

init() {
    PARTITIONS_WRITABLE=()
}

run() {
    local RETURN=$CHECK_SUCCESS

    if [ ${#PARTITIONS_WRITABLE[@]} == 0 ]
    then
        abort "no partition writable to check"
        return $CHECK_IGNORED
    fi

    for PARTITION in ${PARTITIONS_WRITABLE[@]}
    do
        if ! mountpoint -q $PARTITION
        then
            alert "$PARTITION is not a partition..."
            RETURN=$(max $? $RETURN)
        fi

        if ! touch $PARTITION/.host-tool-check 2>/dev/null
        then
            alert "$PARTITION is not a writable"
            RETURN=$(max $? $RETURN)
        else
            echo "$PARTITION is writable"
        fi
        rm -f $PARTITION/.host-tool-check
    done

    return $RETURN
}

