#!/bin/bash

DESCRIPTION="check security upgrade"

init() {
    return 0
}

run() {

    explain "checking security package to upgrade"

    if ! which apt-get >/dev/null
    then
        abort "apt-get not found, I only know debian systems [ignoring test]"
        return $CHECK_IMPOSSIBLE
    fi

    local RETURN=$CHECK_SUCCESS

    apt-get update >$TMPDIR/security-update.list 2>&1
    if grep -q '^[WE]:' $TMPDIR/security-update.list
    then
        alert "got warning in apt-get update"
        RETURN=$(max $? $RETURN)
        cat $TMPDIR/security-update.list
    fi

    apt-get upgrade -s >$TMPDIR/security-upgrade.list 2>&1
    if grep -i security $TMPDIR/security-upgrade.list
    then
        grep -i security $TMPDIR/security-upgrade.list
        alert "system has security packages to upgrade"
        RETURN=$(max $? $RETURN)
    fi

    apt-get clean >/dev/null 2>/dev/null
    #apt-get auto-clean

    rm -f $TMPDIR/security-upgrade.list
    rm -f $TMPDIR/security-update.list

    return $RETURN
}

