#!/bin/bash

DESCRIPTION="replace me"

run() {

    explain "checking security package to upgrade"

    if ! which apt-get >/dev/null
    then
           abort "apt-get not found, I only know debian systems [ignoring test]"
           return
    fi

    apt-get update >/tmp/security-update.list 2>&1
    if grep -q '^[WE]:' /tmp/security-update.list
    then
        alert "got warning in apt-get update"
        cat /tmp/security-update.list
    fi

    apt-get upgrade -s >/tmp/security-upgrade.list 2>&1
    if grep -i security /tmp/security-upgrade.list
    then
        grep -i security /tmp/security-upgrade.list
        alert "system has security packages to upgrade"
    fi

    apt-get clean >/dev/null 2>/dev/null
    #apt-get auto-clean

    rm -f /tmp/security-upgrade.list
    rm -f /tmp/security-update.list
}

