#!/bin/bash

DESCRIPTION="check security upgrade"

init() {
    return 0
}

run() {

    explain "checking security package to upgrade"

    if ! which apt-get >/dev/null
    then
        abort "apt-get not found, I only know debian systems [ignoring test]"
        return $CHECK_IMPOSSIBLE
    fi

    local RETURN=$CHECK_SUCCESS
    local UPDATE=1

    test -e $SELFVARDIR || mkdir -p $SELFVARDIR
    if [[ -e $SELFVARDIR/lastupdate ]]
    then
        local NOW=$(date '+%s')
        local LASTUPDATE=$(stat --format='%Y' $SELFVARDIR/lastupdate)

        if [[ $(( $NOW - $LASTUPDATE )) -le 3600 ]]
        then
            # no need to update
            UPDATE=0
            echo "recent check, no need to update database"
        fi
    fi

    if [[ $UPDATE -eq 1 ]]
    then
        echo "updating database..."
        touch $SELFVARDIR/lastupdate
        apt-get update >$TMPDIR/security-update.list 2>&1
        if grep -q '^[WE]:' $TMPDIR/security-update.list
        then
            alert "got warning in apt-get update"
            RETURN=$(max $? $RETURN)
            cat $TMPDIR/security-update.list
        fi
    fi

    apt-get upgrade -s >$TMPDIR/security-upgrade.list 2>&1
    if grep -q -i security $TMPDIR/security-upgrade.list
    then
        LIST="$(grep -i security $TMPDIR/security-upgrade.list | grep ^Inst | awk '{print "  " $2}')"
        alert "system has security packages to upgrade"$'\n'"$LIST"
        RETURN=$(max $? $RETURN)
    fi

    apt-get clean >/dev/null 2>/dev/null
    #apt-get auto-clean

    rm -f $TMPDIR/security-upgrade.list
    rm -f $TMPDIR/security-update.list

    return $RETURN
}

