#!/bin/bash

SOURCE=$( readlink -f $(dirname $0)"/.." )
TARGET=/usr/local

cp $SOURCE/etc/update-motd.d_host-99-host-tools /etc/update-motd.d/99-host-tools

# TODO: add snapshot
for SCRIPT in host-tools net-4g-stick
do
	cp $SOURCE/bin/$SCRIPT $TARGET/sbin/$SCRIPT
done

