#!/bin/bash

CONFIG="/etc/vanbelle/check-health.conf"

load_config() {

	echo loading configuration

	if ! [ -e $CONFIG ]
	then
		alert "configuration $CONFIG not found"
		exit 1
	fi

	# load config
	source $CONFIG

}

HOSTNAME=$(hostname)

load_config

if [ -n "$WEBHOOK" ]
then
	curl -s -q ${WEBHOOK}${HOSTNAME}'%20must%20be%20checked' >/dev/null
else
	echo WEBHOOK not defined in $CONFIG
fi




